// Generated by `pnpm db:types:linked` from the linked Supabase project. Do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  graphql_public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      graphql: {
        Args: {
          extensions?: Json;
          operationName?: string;
          query?: string;
          variables?: Json;
        };
        Returns: Json;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  public: {
    Tables: {
      branches: {
        Row: {
          address_line: string;
          business_id: string;
          city: string;
          created_at: string;
          google_place_id: string | null;
          id: string;
          location: unknown;
          name: string;
          phone: string | null;
        };
        Insert: {
          address_line: string;
          business_id: string;
          city: string;
          created_at?: string;
          google_place_id?: string | null;
          id?: string;
          location: unknown;
          name: string;
          phone?: string | null;
        };
        Update: {
          address_line?: string;
          business_id?: string;
          city?: string;
          created_at?: string;
          google_place_id?: string | null;
          id?: string;
          location?: unknown;
          name?: string;
          phone?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'branches_business_id_fkey';
            columns: ['business_id'];
            isOneToOne: false;
            referencedRelation: 'businesses';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'branches_business_id_fkey';
            columns: ['business_id'];
            isOneToOne: false;
            referencedRelation: 'businesses_public';
            referencedColumns: ['id'];
          },
        ];
      };
      business_followers: {
        Row: {
          business_id: string;
          consumer_id: string;
          created_at: string;
          notify: boolean;
        };
        Insert: {
          business_id: string;
          consumer_id: string;
          created_at?: string;
          notify?: boolean;
        };
        Update: {
          business_id?: string;
          consumer_id?: string;
          created_at?: string;
          notify?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: 'business_followers_business_id_fkey';
            columns: ['business_id'];
            isOneToOne: false;
            referencedRelation: 'businesses';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'business_followers_business_id_fkey';
            columns: ['business_id'];
            isOneToOne: false;
            referencedRelation: 'businesses_public';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'business_followers_consumer_id_fkey';
            columns: ['consumer_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      businesses: {
        Row: {
          category: Database['public']['Enums']['business_category'];
          created_at: string;
          description: string | null;
          display_name: string;
          id: string;
          legal_name: string;
          logo_path: string | null;
          nit: string;
          owner_id: string;
          updated_at: string;
          verification_status: Database['public']['Enums']['verification_status'];
          verified_at: string | null;
          verified_by: string | null;
        };
        Insert: {
          category: Database['public']['Enums']['business_category'];
          created_at?: string;
          description?: string | null;
          display_name: string;
          id?: string;
          legal_name: string;
          logo_path?: string | null;
          nit: string;
          owner_id: string;
          updated_at?: string;
          verification_status?: Database['public']['Enums']['verification_status'];
          verified_at?: string | null;
          verified_by?: string | null;
        };
        Update: {
          category?: Database['public']['Enums']['business_category'];
          created_at?: string;
          description?: string | null;
          display_name?: string;
          id?: string;
          legal_name?: string;
          logo_path?: string | null;
          nit?: string;
          owner_id?: string;
          updated_at?: string;
          verification_status?: Database['public']['Enums']['verification_status'];
          verified_at?: string | null;
          verified_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'businesses_owner_id_fkey';
            columns: ['owner_id'];
            isOneToOne: true;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'businesses_verified_by_fkey';
            columns: ['verified_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      coupons: {
        Row: {
          business_id: string;
          created_at: string;
          description: string | null;
          discount_type: Database['public']['Enums']['discount_type'];
          discount_value: number | null;
          id: string;
          image_path: string | null;
          is_active: boolean;
          terms: string | null;
          title: string;
          updated_at: string;
          valid_from: string | null;
          valid_until: string | null;
        };
        Insert: {
          business_id: string;
          created_at?: string;
          description?: string | null;
          discount_type: Database['public']['Enums']['discount_type'];
          discount_value?: number | null;
          id?: string;
          image_path?: string | null;
          is_active?: boolean;
          terms?: string | null;
          title: string;
          updated_at?: string;
          valid_from?: string | null;
          valid_until?: string | null;
        };
        Update: {
          business_id?: string;
          created_at?: string;
          description?: string | null;
          discount_type?: Database['public']['Enums']['discount_type'];
          discount_value?: number | null;
          id?: string;
          image_path?: string | null;
          is_active?: boolean;
          terms?: string | null;
          title?: string;
          updated_at?: string;
          valid_from?: string | null;
          valid_until?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'coupons_business_id_fkey';
            columns: ['business_id'];
            isOneToOne: false;
            referencedRelation: 'businesses';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'coupons_business_id_fkey';
            columns: ['business_id'];
            isOneToOne: false;
            referencedRelation: 'businesses_public';
            referencedColumns: ['id'];
          },
        ];
      };
      payments: {
        Row: {
          amount_cents: number;
          attempt: number;
          created_at: string;
          currency: string;
          id: string;
          period_end: string | null;
          period_start: string | null;
          raw: Json | null;
          reference: string;
          status: Database['public']['Enums']['payment_status'];
          subscription_id: string;
          updated_at: string;
          wompi_transaction_id: string | null;
        };
        Insert: {
          amount_cents: number;
          attempt?: number;
          created_at?: string;
          currency?: string;
          id?: string;
          period_end?: string | null;
          period_start?: string | null;
          raw?: Json | null;
          reference: string;
          status?: Database['public']['Enums']['payment_status'];
          subscription_id: string;
          updated_at?: string;
          wompi_transaction_id?: string | null;
        };
        Update: {
          amount_cents?: number;
          attempt?: number;
          created_at?: string;
          currency?: string;
          id?: string;
          period_end?: string | null;
          period_start?: string | null;
          raw?: Json | null;
          reference?: string;
          status?: Database['public']['Enums']['payment_status'];
          subscription_id?: string;
          updated_at?: string;
          wompi_transaction_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'payments_subscription_id_fkey';
            columns: ['subscription_id'];
            isOneToOne: false;
            referencedRelation: 'subscriptions';
            referencedColumns: ['id'];
          },
        ];
      };
      profiles: {
        Row: {
          created_at: string;
          full_name: string | null;
          id: string;
          phone: string | null;
          role: Database['public']['Enums']['user_role'];
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          full_name?: string | null;
          id: string;
          phone?: string | null;
          role?: Database['public']['Enums']['user_role'];
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          full_name?: string | null;
          id?: string;
          phone?: string | null;
          role?: Database['public']['Enums']['user_role'];
          updated_at?: string;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          consumer_id: string;
          created_at: string;
          endpoint: string;
          id: string;
          keys: Json;
          user_agent: string | null;
        };
        Insert: {
          consumer_id: string;
          created_at?: string;
          endpoint: string;
          id?: string;
          keys: Json;
          user_agent?: string | null;
        };
        Update: {
          consumer_id?: string;
          created_at?: string;
          endpoint?: string;
          id?: string;
          keys?: Json;
          user_agent?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'push_subscriptions_consumer_id_fkey';
            columns: ['consumer_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      redemptions: {
        Row: {
          branch_id: string | null;
          business_id: string;
          consumer_id: string;
          coupon_id: string;
          id: string;
          scanned_at: string;
          scanned_by: string;
          subscription_status_at_scan: Database['public']['Enums']['subscription_status'];
          token_jti: string;
        };
        Insert: {
          branch_id?: string | null;
          business_id: string;
          consumer_id: string;
          coupon_id: string;
          id?: string;
          scanned_at?: string;
          scanned_by: string;
          subscription_status_at_scan: Database['public']['Enums']['subscription_status'];
          token_jti: string;
        };
        Update: {
          branch_id?: string | null;
          business_id?: string;
          consumer_id?: string;
          coupon_id?: string;
          id?: string;
          scanned_at?: string;
          scanned_by?: string;
          subscription_status_at_scan?: Database['public']['Enums']['subscription_status'];
          token_jti?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'redemptions_branch_id_fkey';
            columns: ['branch_id'];
            isOneToOne: false;
            referencedRelation: 'branches';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'redemptions_business_id_fkey';
            columns: ['business_id'];
            isOneToOne: false;
            referencedRelation: 'businesses';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'redemptions_business_id_fkey';
            columns: ['business_id'];
            isOneToOne: false;
            referencedRelation: 'businesses_public';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'redemptions_consumer_id_fkey';
            columns: ['consumer_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'redemptions_coupon_id_fkey';
            columns: ['coupon_id'];
            isOneToOne: false;
            referencedRelation: 'coupons';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'redemptions_scanned_by_fkey';
            columns: ['scanned_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      subscriptions: {
        Row: {
          canceled_at: string | null;
          card_brand: string | null;
          card_last4: string | null;
          charge_attempts: number;
          consumer_id: string;
          created_at: string;
          current_period_end: string | null;
          id: string;
          next_charge_at: string | null;
          status: Database['public']['Enums']['subscription_status'];
          trial_ends_at: string;
          updated_at: string;
          wompi_customer_email: string;
          wompi_payment_source_id: number | null;
        };
        Insert: {
          canceled_at?: string | null;
          card_brand?: string | null;
          card_last4?: string | null;
          charge_attempts?: number;
          consumer_id: string;
          created_at?: string;
          current_period_end?: string | null;
          id?: string;
          next_charge_at?: string | null;
          status?: Database['public']['Enums']['subscription_status'];
          trial_ends_at: string;
          updated_at?: string;
          wompi_customer_email: string;
          wompi_payment_source_id?: number | null;
        };
        Update: {
          canceled_at?: string | null;
          card_brand?: string | null;
          card_last4?: string | null;
          charge_attempts?: number;
          consumer_id?: string;
          created_at?: string;
          current_period_end?: string | null;
          id?: string;
          next_charge_at?: string | null;
          status?: Database['public']['Enums']['subscription_status'];
          trial_ends_at?: string;
          updated_at?: string;
          wompi_customer_email?: string;
          wompi_payment_source_id?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: 'subscriptions_consumer_id_fkey';
            columns: ['consumer_id'];
            isOneToOne: true;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      wompi_events: {
        Row: {
          checksum: string;
          environment: string;
          event_type: string;
          payload: Json;
          processed_at: string | null;
          received_at: string;
          wompi_transaction_id: string | null;
        };
        Insert: {
          checksum: string;
          environment: string;
          event_type: string;
          payload: Json;
          processed_at?: string | null;
          received_at?: string;
          wompi_transaction_id?: string | null;
        };
        Update: {
          checksum?: string;
          environment?: string;
          event_type?: string;
          payload?: Json;
          processed_at?: string | null;
          received_at?: string;
          wompi_transaction_id?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      businesses_public: {
        Row: {
          active_coupon_count: number | null;
          best_score: number | null;
          category: Database['public']['Enums']['business_category'] | null;
          description: string | null;
          display_name: string | null;
          id: string | null;
          logo_path: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      app_role: {
        Args: never;
        Returns: Database['public']['Enums']['user_role'];
      };
      coupon_is_live: {
        Args: { c: Database['public']['Tables']['coupons']['Row'] };
        Returns: boolean;
      };
      coupon_score: {
        Args: { t: Database['public']['Enums']['discount_type']; v: number };
        Returns: number;
      };
      is_admin: { Args: never; Returns: boolean };
      issue_coupon_token: { Args: { p_coupon_id: string }; Returns: string };
      nearby_businesses: {
        Args: {
          p_category?: Database['public']['Enums']['business_category'];
          p_lat: number;
          p_limit?: number;
          p_lng: number;
          p_radius_m?: number;
          p_sort?: string;
        };
        Returns: {
          active_coupon_count: number;
          address_line: string;
          best_score: number;
          branch_id: string;
          branch_name: string;
          business_id: string;
          category: Database['public']['Enums']['business_category'];
          display_name: string;
          distance_m: number;
          lat: number;
          lng: number;
          logo_path: string;
        }[];
      };
      subscription_access_until: {
        Args: { s: Database['public']['Tables']['subscriptions']['Row'] };
        Returns: string;
      };
      verify_coupon_token: {
        Args: { p_branch_id?: string; p_token: string };
        Returns: Json;
      };
    };
    Enums: {
      business_category: 'restaurants' | 'beverages' | 'desserts' | 'retail';
      discount_type: 'percentage' | 'fixed' | 'bogo' | 'other';
      payment_status: 'pending' | 'approved' | 'declined' | 'voided' | 'error';
      subscription_status: 'trialing' | 'active' | 'past_due' | 'canceled';
      user_role: 'consumer' | 'business' | 'admin';
      verification_status: 'pending' | 'verified' | 'rejected';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  'public'
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      business_category: ['restaurants', 'beverages', 'desserts', 'retail'],
      discount_type: ['percentage', 'fixed', 'bogo', 'other'],
      payment_status: ['pending', 'approved', 'declined', 'voided', 'error'],
      subscription_status: ['trialing', 'active', 'past_due', 'canceled'],
      user_role: ['consumer', 'business', 'admin'],
      verification_status: ['pending', 'verified', 'rejected'],
    },
  },
} as const;
