name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm nx format:check --base="remotes/origin/main"
      - run: pnpm nx sync:check
      - run: pnpm nx affected -t lint test typecheck build --base="remotes/origin/main"

  database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase start -x studio,realtime,storage-api,imgproxy,edge-runtime,logflare,vector,supavisor
      - run: supabase test db
      - run: supabase stop
        if: always()
